### PR TITLE
Let setuptools include LICENSE automatically

### LINKED ISSUE #139: LICENSE being installed to the wrong path
As specified currently in setup.py with

```python
config['data_files'] = [('', ['LICENSE'])]
```

this gets installed right into `sys.prefix` (or causes an error with homebrew python):

```
$ pip install anytree
Collecting anytree
  Using cached anytree-2.8.0-py2.py3-none-any.whl (41 kB)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.8/site-packages (from anytree) (1.15.0)
Installing collected packages: anytree
ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/local/LICENSE'
Consider using the `--user` option or check the permissions.
```

Per https://github.com/pypa/setuptools/pull/1536 this should not be necessary, rather `license_file` can be specified instead.

### PR DESCRIPTION
**Pull request by paper42**
fixes #139

### CODE REVIEW

**Comment by teauxfu** [comment]
may be superseded by #172

**Comment by c0fec0de** [comment]
Merged. Thanks for contributing.

**Comment by cbrnr** [comment]
Any chance you could make a new release which includes this change @c0fec0de? Currently, installing `anytree` on macOS still produces the permission error.

**Comment by cbrnr** [comment]
Also, it seems like this change has not been merged into `master`.

**Comment by paper42** [comment]
> Also, it seems like this change has not been merged into `master`.

The patch from this PR has been merged to the devel branch. It seems like development happens there and on a release, it gets pulled into master.

> Any chance you could make a new release which includes this change @c0fec0de? Currently, installing `anytree` on macOS still produces the permission error.

I worked around this on Linux by removing the file from our distribution package, maybe something like this is also possible with homebrew on MacOS? You could try contacting the package maintainer.

**Comment by cbrnr** [comment]
Thanks @paper42! I can't use that workaround because I'm not installing the package via Homebrew. I'm using `pip install anytree`. The package does get installed despite the error, but I think this should still be fixed.

**Pull request closed without merging**
